### ISSUE TITLE
Pageview Tracking

### ISSUE THREAD

**Issue by claytondaley** [claytondaley/DAM4#3]
Get Piwik integrated for pageview tracking
- [x] For legacy code, use PHP tracker
- [ ] Use API connection to get tracking code (see if Piwik UI component can be repurposed)
- [ ] Consider a more general module for optional support of other providers

**Comment by claytondaley** [comment]
fixed for legacy code

**Comment by claytondaley** [comment]
Tracking of legacy pages (using server-side tracking) is now available.
